name: Create Branch from Issue

on:
  issues:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Create and push branch
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          ISSUE_TITLE=${{ github.event.issue.title }}
          SAFE_TITLE=$(echo "$ISSUE_TITLE" | tr ' ' '-' | tr -cd '[:alnum:]-')

          BRANCH_NAME="issue-${ISSUE_NUMBER}-${SAFE_TITLE}"

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git checkout main
          git pull origin main
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
